---
variables:

default:
  artifacts:
    expire_in:
      3 day

include:
  # cf: https://docs.gitlab.com/ee/ci/yaml/includes.html
  - ".gitlab/ci/workflow.yml"
  - ".gitlab/ci/stages.yml"
  - ".gitlab/ci/core.yml"

  - ".gitlab/ci/pre-commit.yml"

  - ".gitlab/ci/releases.yml"
  - ".gitlab/ci/pages.yml"

pre-commit:
  extends: .pre-commit

pre-commit:autoupdate:
  extends: .pre-commit:autoupdate


.gitlab:release:
  extends: .gitlab:release
  needs:
    # Require pre-commit to force nitpick check
    - job: pre-commit
      artifacts: false
